name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install conda environment
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          activate-environment: env
          environment-file: environment.yml
          python-version: 3.8

      - name: GitHub Action for pytest
        uses: cclauss/GitHub-Action-for-pytest@0.5.0
